authors/urls.py
from django.urls import path

urlpatterns = [

]

books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.list, name="list"),
    path("<int:book_id>/", views.details, name="details"),
]

flashcards/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
    path("", views.listview, name="list"),
    path("<int:post_id>", views.details, name="details"),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("authors/", include("authors.urls")),
    path("books/", include("books.urls")),
    path("posts/", include("posts.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("users.urls")),
]

users/urls.py
from django.urls import path
from .views import dashboard, example_view


urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("examples/formform", example_view, name="example_view"),
]

authors/models.py
from django.db import models


# Create your models here.
class Autor(models.Model):
    imie = models.CharField(max_length=200)
    nazwisko = models.CharField(max_length=200)
    wiek = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.imie} {self.nazwisko}"

books/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    year = models.IntegerField()
    author = models.ForeignKey(
        "authors.Autor", on_delete=models.CASCADE, related_name="books"
    )

    def __str__(self):
        return self.title

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms


class AddPost(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)

users/forms.py
from django import forms


class NameForm(forms.Form):
    your_name = forms.CharField()
    email = forms.EmailField()

    def clean_email(self):
        if self.cleaned_data["email"] != "rkorzen@wp.pl":
            raise forms.ValidationError("Wrong email")

authors/views.py
from django.shortcuts import render

# Create your views here.
from authors.models import Autor


def details(request, author_id):
    author = Autor.objects.get(pk=author_id)

    context = {"author": author}
    return render(request, "authors/details.html", context)


def list(request):
    authors = Autor.objects.all()

    context = {"authors": authors}
    return render(request, "authors/list.html", context)

books/views.py
from django.shortcuts import render

# Create your views here.
from books.models import Book


def details(request, book_id):
    book = Book.objects.get(pk=book_id)

    context = {"book": book}
    return render(request, "books/details.html", context)


def list(request):
    books = Book.objects.all()

    context = {"books": books}
    return render(request, "books/list.html", context)

posts/views.py
from django.shortcuts import render

# Create your views here.
from posts.models import Post
from posts.forms import AddPost


def listview(request):
    posts = Post.objects.all()
    print(request.method)
    print(request.user)
    if request.method == "POST":
        form = AddPost(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            Post.objects.create(title=title, content=content, author=request.user)

    form = AddPost()
    context = {"posts": posts, "form": form}
    return render(request, "posts/list.html", context)


def details(request, post_id):
    post = Post.objects.get(pk=post_id)

    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")

        post.title = title
        post.content = content
        post.save()

    context = {"post": post}
    return render(request, "posts/details.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.
from users.forms import NameForm


def dashboard(request):
    return render(request, "base.html")


def example_view(request):

    if request.method == "POST":
        form = NameForm(data=request.POST)

        print(form.data)

    form = NameForm()
    context = {"form": form}

    return render(request, "users/example.html", context)

templates/authors/details.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ author }}</h1>

<h2>Publikacje</h2>

<ul>
{% for book in author.books.all %}
    <li><a href="{% url 'books:details' book.id %}">{{ book.title }}</a></li>
{% endfor %}
    </ul>

<a href="{% url 'authors:list' %}">Lista autorów</a>

{% endblock %}

templates/authors/list.html
{% extends 'base.html' %}

{% block content %}

Autorzy


{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.css"
  rel="stylesheet"
/>

</head>
<body>
<div class="container">
    {% include 'includes/header.html' %}
</div>
{% block content %}

Strona Główna

{% endblock %}

<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.js"
></script>
<script src="https://cdn.jsdelivr.net/gh/Wruczek/Bootstrap-Cookie-Alert@gh-pages/cookiealert.js"></script>
</body>
</html>

templates/books/details.html
{% extends 'base.html' %}

{% block content %}

Books list

<a href="{% url 'books:list' %}">Lista książek</a>


{% endblock %}

templates/books/list.html
Books list

templates/flashcards/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/login_popup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/price.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/profile/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/register_popup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/flashcards/shop.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/includes/header.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarExample01"
        aria-controls="navbarExample01"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarExample01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:list' %}">Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:list' %}">Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authors:list' %}">Author</a>
          </li>
          <li>
            <input
        type="search"
        class="form-control rounded"
        placeholder="Search"
        aria-label="Search"
        aria-describedby="search-addon"
      />
          </li>
          <li>
      <span class="input-group-text border-0" id="search-addon">
        <i class="fas fa-search"></i>
      </span>
          </li>
        </ul>

          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'login' %}">Login</a>
          {% endif %}
      </div>
    </div>
  </nav>
  <!-- Navbar -->

templates/posts/details.html
{% extends 'base.html' %}
{% block content %}



<h1>{{ post.title }}</h1>
<small>By: {{ post.author }}</small>
<p>{{ post.content }}</p>

{% if user == post.author %}
{% include 'posts/includes/post_form.html' %}
{% endif %}




{% endblock %}

templates/posts/includes/comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/posts/includes/post_form.html
<form method="POST">
    {% csrf_token %}
    <p>
        <label for="title">Tytuł</label>
        <input type="text" id="title" name="title" value="{{ post.title }}" >
    </p>
    <p>
        <label for="content">Treść</label>
        <textarea id="content" name="content" placeholder="treść...." >{{ post.content }}</textarea>
    </p>
    <input type="submit" value="send">
</form>

templates/posts/list.html
{% extends 'base.html' %}

{% block content %}

<h1>Posty</h1>

<ul>
{% for p in posts %}
<li><a href="#">{{ p }}</a></li>
{% endfor %}
</ul>

{% if user.is_authenticated %}

<!--{% include 'posts/includes/post_form.html' %}-->

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
</form>

{% endif %}
{% endblock %}

templates/users/example.html
{% extends 'base.html' %}
{% block content %}



<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
</form>

{% endblock %}